# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Apr 27 15:04:18 2011
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(872,902)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtGui.QGraphicsView(Dialog)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.classification_box = QtGui.QWidget(Dialog)
        self.classification_box.setMaximumSize(QtCore.QSize(16777215,50))
        self.classification_box.setObjectName("classification_box")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.classification_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileName = QtGui.QTextBrowser(self.classification_box)
        self.fileName.setMinimumSize(QtCore.QSize(132,27))
        self.fileName.setMaximumSize(QtCore.QSize(200,27))
        self.fileName.setObjectName("fileName")
        self.horizontalLayout_2.addWidget(self.fileName)
        spacerItem = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.grp_class_controls = QtGui.QWidget(self.classification_box)
        self.grp_class_controls.setEnabled(False)
        self.grp_class_controls.setAcceptDrops(False)
        self.grp_class_controls.setObjectName("grp_class_controls")
        self.scene_classification_box = QtGui.QHBoxLayout(self.grp_class_controls)
        self.scene_classification_box.setObjectName("scene_classification_box")
        self.rb_outside = QtGui.QRadioButton(self.grp_class_controls)
        self.rb_outside.setObjectName("rb_outside")
        self.scene_classification_box.addWidget(self.rb_outside)
        self.rb_inside = QtGui.QRadioButton(self.grp_class_controls)
        self.rb_inside.setAutoRepeat(False)
        self.rb_inside.setObjectName("rb_inside")
        self.scene_classification_box.addWidget(self.rb_inside)
        self.rb_junk = QtGui.QRadioButton(self.grp_class_controls)
        self.rb_junk.setObjectName("rb_junk")
        self.scene_classification_box.addWidget(self.rb_junk)
        self.horizontalLayout_2.addWidget(self.grp_class_controls)
        self.verticalLayout_3.addWidget(self.classification_box)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setMaximumSize(QtCore.QSize(16777215,50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_open = QtGui.QPushButton(self.widget)
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_3.addWidget(self.btn_open)
        self.btn_classdir = QtGui.QPushButton(self.widget)
        self.btn_classdir.setMaximumSize(QtCore.QSize(132,27))
        self.btn_classdir.setObjectName("btn_classdir")
        self.horizontalLayout_3.addWidget(self.btn_classdir)
        spacerItem1 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.widget)
        self.controlls = QtGui.QVBoxLayout()
        self.controlls.setObjectName("controlls")
        self.control_buttons = QtGui.QWidget(Dialog)
        self.control_buttons.setEnabled(False)
        self.control_buttons.setObjectName("control_buttons")
        self.horizontalLayout = QtGui.QHBoxLayout(self.control_buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cb_unlassified = QtGui.QCheckBox(self.control_buttons)
        self.cb_unlassified.setObjectName("cb_unlassified")
        self.horizontalLayout.addWidget(self.cb_unlassified)
        spacerItem2 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.commandLinkButton_2 = QtGui.QCommandLinkButton(self.control_buttons)
        self.commandLinkButton_2.setCheckable(False)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.horizontalLayout.addWidget(self.commandLinkButton_2)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.control_buttons)
        self.commandLinkButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout.addWidget(self.commandLinkButton)
        self.controlls.addWidget(self.control_buttons)
        self.verticalLayout_3.addLayout(self.controlls)
        self.Inside = QtGui.QAction(Dialog)
        self.Inside.setCheckable(True)
        self.Inside.setChecked(False)
        self.Inside.setAutoRepeat(False)
        self.Inside.setObjectName("Inside")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.commandLinkButton_2,self.graphicsView)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_outside.setText(QtGui.QApplication.translate("Dialog", "Outside", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_outside.setShortcut(QtGui.QApplication.translate("Dialog", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_inside.setText(QtGui.QApplication.translate("Dialog", "Inside", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_inside.setShortcut(QtGui.QApplication.translate("Dialog", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_junk.setText(QtGui.QApplication.translate("Dialog", "Junk", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_junk.setShortcut(QtGui.QApplication.translate("Dialog", "J", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_open.setText(QtGui.QApplication.translate("Dialog", "Open Image Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_classdir.setText(QtGui.QApplication.translate("Dialog", "Choose output dir", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_unlassified.setText(QtGui.QApplication.translate("Dialog", "Show unclassified only", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton_2.setText(QtGui.QApplication.translate("Dialog", "Prev", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton_2.setShortcut(QtGui.QApplication.translate("Dialog", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setText(QtGui.QApplication.translate("Dialog", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setShortcut(QtGui.QApplication.translate("Dialog", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.Inside.setText(QtGui.QApplication.translate("Dialog", "Inside", None, QtGui.QApplication.UnicodeUTF8))
        self.Inside.setShortcut(QtGui.QApplication.translate("Dialog", "I", None, QtGui.QApplication.UnicodeUTF8))

